### PR TITLE
New Getting Started section (including Vagrant), swap -> popcount, and a crack at helpers.saw

### PR DESCRIPTION
**Pull request by dylanmc**
In going through Getting Started, I couldn't get SAW working on my macOS machine (XCode's clang incompatible), so I used Vagrant, and it was great, so added that as an option (for folks who don't already Docker).

I pulled in popcount for the first example, because it's less tricky (don't need to worry about pointers), and it's also kind  of super-exciting. 

TODO: a new intermediate chapter that pulls in the swap example and how to deal with memory and pointers (extending helpers.saw as needed), then to rewrite the Salsa and HMAC chapters to use those helpers.

### CODE REVIEW

**Comment by david-christiansen** [comment]
It looks to me like you forgot to commit `examples/Vagrantfile`. Mind pushing it?

**Comment by dylanmc** [comment]
Good catch. It has been pushed. Do I need to do anything with this pull request?

**Comment by david-christiansen** [comment]
Nope, the push updates it automatically.

It also dumps a bunch of warnings about renamed files while I build it, but I can fix that stuff.

**Comment by david-christiansen** [comment]
I think something might have gone wrong with your push. The text goes immediately into swap, just as it did before, rather than starting with popcount. Can you check that the code here on Github matches your local machine?

**Comment by david-christiansen** [comment]
I don't see the popcount chapter. Did that also not get pushed?

**Comment by dylanmc** [comment]
You're sure right - I did a git add / commit / push on the files here (for example IntroToSaw.rst), but indeed they're not on Github. Huh. I see in the pull request my set of commits, but in my fork on github they're not there. 

I'm sure new at this! I'll poke around to see what's up.

**Comment by david-christiansen** [comment]
It might be a different branch?

**Pull request merged**
