### PR TITLE
propagating helpers.saw changes, incorporating atomb's & audmcname's suggestions

### PR DESCRIPTION
**Pull request by dylanmc**
TODO - double-check that once the whole repo is published, the examples.tgz unpacked, then `vagrant up` / `vagrant ssh` puts folks into the expected state.

### CODE REVIEW

**Review by atomb — CHANGES_REQUESTED** [review]
These changes look great! It looks as though the change includes the binary for the `minmax` example, though. Would it be easy to remove that?

**Comment by dylanmc** [comment]
I swore I took it out - I'll check again.

**Comment by atomb** [comment]
Oops. I misread the diff. All is good.

**Review by atomb — APPROVED** [review]
Looks good!

**Pull request merged**
